#!/bin/bash
# Copyright (c) 2024 RFull Development
# This source code is managed under the MIT license. See LICENSE in the project root.
docker buildx build --platform=linux/amd64,linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
